name: animal_type_classificiation_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.5.0
  image_picker: ^1.1.2
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  flutter_tts: ^3.8.5
  speech_to_text: ^6.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
