// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4SNfjiKBIq4q5tKNMbZAJeZ3bVLXIQgc',
    appId: '1:1017908629557:web:dde924a7bcb7a54c7aa17c',
    messagingSenderId: '1017908629557',
    projectId: 'smartindiahackathon-bce21',
    authDomain: 'smartindiahackathon-bce21.firebaseapp.com',
    storageBucket: 'smartindiahackathon-bce21.firebasestorage.app',
    measurementId: 'G-ZKYV06XNJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH54B2OiCjHF2Maz0oAXNtG8VKQeuYtkA',
    appId: '1:1017908629557:android:be87d5c1bf090c0b7aa17c',
    messagingSenderId: '1017908629557',
    projectId: 'smartindiahackathon-bce21',
    storageBucket: 'smartindiahackathon-bce21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwB_TDRy6IdgQD7CKp5zLEDNorPtWqtPU',
    appId: '1:1017908629557:ios:ae62f7be8f6471177aa17c',
    messagingSenderId: '1017908629557',
    projectId: 'smartindiahackathon-bce21',
    storageBucket: 'smartindiahackathon-bce21.firebasestorage.app',
    iosBundleId: 'com.example.animalTypeClassificiationApp',
  );
}
